[versions]
# config
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
# __(API)_(feature)___(version)_(abi)
# TODO: Feature bit is no longer useful, drop when next api releases
versionCode = "3411090"
versionCodeAlpha = "17"
versionName = "2.0.3"
compose-compiler = "1.5.12" # https://androidx.dev/storage/compose-compiler/repository

# libraries
accompanist = "0.30.1"
activity-compose = "1.9.0"
appcompat = "1.7.0"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
junit = "4.13.2"
compose-bom = "2024.05.00"
core-ktx = "1.13.1"
core-splashscreen = "1.0.1"
gson = "2.10.1"
hilt-android = "2.49"
hilt-android-compiler = "2.48"
hilt-navigation-compose = "1.2.0"
hilt-work = "1.2.0"
navigation-compose = "2.7.7"
okhttp = "4.12.0"
retrofit = "2.9.0"
libsu = "PR182-SNAPSHOT" # TODO Force enable the latest libsu
work-manager = "2.9.1"
zip4j = "2.11.5"
kotlinx-coroutines-core-jvm = "1.8.0"
room = "2.6.1"
coil-compose = "2.4.0"
dotlottie-android = "0.2.0"
palette = "1.0.0"
google-services = "4.3.15" # Pinned: https://github.com/firebase/firebase-android-sdk/issues/4693#issuecomment-1765778239
firebase-crashlytics-gradle = "2.9.9" # Workaround: https://github.com/xamarin/GooglePlayServicesComponents/issues/642#issuecomment-1221520982
firebase-bom = "32.7.0"
pickyou = "2.1.8"
datastore-preferences = "1.1.1"
serialization-protobuf = "1.6.0"
apache-commons = "3.10.0"
apache-commons-codec = "1.16.1"
smbj = "0.11.5"
smbj-rpc = "0.12.0"
sshj = "0.38.0"
guava-compat = "9999.0-empty-to-avoid-conflict-with-guava"
sardine-next = "1.0.2"
bountycastle = "1.76"
animation-graphics = "1.6.8"

# plugins
android-gradle-plugin = "8.2.2"
kotlin = "1.9.23"
hilt = "2.48"
hilt-work-compiler = "1.2.0"
ksp-kotlin = "1.9.23-1.0.20"
refine = "4.4.0"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "animation-graphics" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "palette" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-manager" }
bountycastle = { group = "org.bouncycastle", name = "bcutil-jdk18on", version.ref = "bountycastle" }
refine-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "refine" }
refine-annotation-processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "refine" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
dotlottie-android = { module = "com.github.LottieFiles:dotlottie-android", version.ref = "dotlottie-android" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android-compiler" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
hilt-work-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-work-compiler" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines-core-jvm" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
libsu-service = { module = "com.github.topjohnwu.libsu:service", version.ref = "libsu" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
pickyou = { module = "com.github.xayahsususu:libpickyou", version.ref = "pickyou" }
serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization-protobuf" }
apache-commons-net = { module = "commons-net:commons-net", version.ref = "apache-commons" }
apache-commons-codec = { module = "commons-codec:commons-codec", version.ref = "apache-commons-codec" }
smbj = { module = "com.hierynomus:smbj", version.ref = "smbj" }
smbj-rpc = { module = "com.rapid7.client:dcerpc", version.ref = "smbj-rpc" }
sshj = { module = "com.hierynomus:sshj", version.ref = "sshj" }
guava-compat = { module = "com.google.guava:listenablefuture", version.ref = "guava-compat" }
sardine-next = { module = "com.github.xayahsususu:sardine-next", version.ref = "sardine-next" }

# Dependencies of the included build-logic
android-build-logic = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
kotlin-build-logic = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-build-logic = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp-kotlin" }
firebase-crashlytics-build-logic = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
com-android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-kotlin" }
gms-google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
refine = { id = "dev.rikka.tools.refine", version.ref = "refine" }

application-common = { id = "application.common", version = "unspecified" }
application-compose = { id = "application.compose", version = "unspecified" }
application-hilt = { id = "application.hilt", version = "unspecified" }
application-hilt-work = { id = "application.hilt.work", version = "unspecified" }
library-common = { id = "library.common", version = "unspecified" }
library-hilt = { id = "library.hilt", version = "unspecified" }
library-hilt-work = { id = "library.hilt.work", version = "unspecified" }
library-room = { id = "library.room", version = "unspecified" }
library-compose = { id = "library.compose", version = "unspecified" }
library-protobuf = { id = "library.protobuf", version = "unspecified" }
library-test = { id = "library.test", version = "unspecified" }
library-androidTest = { id = "library.androidTest", version = "unspecified" }
library-firebase = { id = "library.firebase", version = "unspecified" }
